# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import codecs
import re

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from binarytree import tree, bst, heap, Node
from src.main import Tree


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 501, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 501, 251))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 300, 501, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 330, 501, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 370, 501, 281))
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.pushButton_2.setText(_translate("MainWindow", "Количество вершин правого поддерева"))
        self.pushButton.clicked.connect(self.file_open)
        self.pushButton_2.clicked.connect(self.input_tree)

    def read_array_from_file(self, file_name):
        file = codecs.open(file_name, 'r')
        array = [list(map(int, line.split())) for line in file]
        return array[0]

    def file_open(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        array = self.read_array_from_file(path)
        self.set_tree(array, self.textEdit)
        return array

    def set_tree(self, array, model):
        tree = Tree()
        for i in range(len(array)):
            tree.add(array[i])
        self.output_tree(tree, model)

    def input_tree(self):
        array = self.lineEdit.text()
        array = re.findall('\d+', array)
        array = [int(numeric_string) for numeric_string in array]
        self.set_tree(array, self.textEdit_2)

    def output_tree(self, tree, model):
        model.append(str("Количество вершин правого поддерева"))
        model.append(str(tree.find()))
        model.append(str((tree.returnTree())))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
